name: Auto Archive
on: push

env:
  CUBOX_API: ${{ secrets.ACCESS_TOKEN }}
  FORUM_URL: ${{ env.FORUM_URL }}

jobs:
  show_environment:
    name: "Show environment variables"
    runs-on: ubuntu-latest
    steps:
      - name: "Show environment variables"
        run: |
          env
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9.6 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run script
        run: |
          python app.py