name: Auto Archive
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.9.6 ]
    outputs:
      PRE_ID: ${{ steps.readPreId.outputs.content }}
      NOW_ID: ${{ steps.readNowId.outputs.content }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: read preId
        id: readPreId
        uses: juliangruber/read-file-action@v1
        with:
          path: ./last.txt
      - name: run script
        env:
          CUBOX_API: ${{ secrets.CUBOX_API }}
          FORUM_URL: ${{ secrets.FORUM_URL }}
        run: |
          python app.py
      - name: read nowId
        id: readNowId
        uses: juliangruber/read-file-action@v1
        with:
          path: ./last.txt

  commit:
    runs-on: ubuntu-20.04
    needs: [ build ]
    if: needs.build.outputs.PRE_ID != needs.build.outputs.NOW_ID
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "new archive" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}